version: "3.8"
networks:
  lan:
services:
  neo4j:
    image: neo4j:4.2.3-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/12345678
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ~/databases/koaPractice/neo4j:/data
